### ISSUE TITLE
Actions artifacts? `actions/upload-artifact@v3`

### ISSUE THREAD

**Issue by brian6932** [ckormanyos/xxd#11]
Repo seems useful, is there a plan to add artifacts to the build ci?

**Comment by ckormanyos** [comment]
> is there a plan to add artifacts to the build ci?

That seems like a good idea. I'll learn how to do it and give it a try here for xxd.

Thanks for the suggestion @brian6932

**Comment by ckormanyos** [comment]
Hello @brian6932 this is fixed in #12 change set f1b84eef2ec2b24245168e62bb5e4e5bd5a1b8b1

**Comment by brian6932** [comment]
Nice
