### ISSUE TITLE
Please provide a release version

### ISSUE THREAD

**Issue by LinArcX** [ckormanyos/xxd#40]
Hi. I want to add xxd to the scoop package manager for windows.

They have a policy that packages should have a stable release version.

Can you please add a release?

**Comment by ckormanyos** [comment]
Hi @LinArcX, thank you for your interest.

> Can you please add a release?

Yes. I'll need a day or two. I'll include Windows, Linux and MacOS so the client can select which one is needed.

**Comment by ckormanyos** [comment]
Done. @LinArcX, please see release [v1.0](https://github.com/ckormanyos/xxd/releases/tag/v1.0).

If anything missing, wrong, compressed the wrong way or there are any other problems whatsoever, please feel free to (reopen and/or) continue this thread.
